#!/usr/bin/env bash
# Spin up N liun-node instances on localhost for development.
#
# Each node gets its own data dir, identity, and a trio of ports:
#   - channel TCP   = CHANNEL_BASE + i
#   - DHT UDP       = DHT_BASE     + i
#   - admin HTTP    = ADMIN_BASE   + i
#
# Node 0 is the "genesis seed": it boots with an empty config.
# Nodes 1..N-1 boot with node 0 as their single DHT seed.
#
# Usage:
#   ./up.sh 5          # start 5 nodes
#   ./up.sh 5 --fresh  # wipe devnet/node-* state first
#
# Logs: devnet/logs/node-N.log
# PIDs: devnet/pids/node-N.pid
#
# Tail a specific node: `./logs.sh 3`
# Tail all:            `./logs.sh`
# Shut down:           `./down.sh`
# Check health:        `./status.sh`

set -euo pipefail

N="${1:-3}"
FRESH="${2:-}"

CHANNEL_BASE=27700
DHT_BASE=27800
ADMIN_BASE=27900

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"
BIN="$REPO/target/release/liun-node"

if [[ ! -x "$BIN" ]]; then
  echo "  → building release binary (one-time)"
  (cd "$REPO" && cargo build --release --bin liun-node)
fi

mkdir -p "$ROOT/logs" "$ROOT/pids"

if [[ "$FRESH" == "--fresh" ]]; then
  echo "  → wiping existing node data"
  rm -rf "$ROOT/node-"*
  rm -f  "$ROOT/logs/node-"*.log "$ROOT/pids/node-"*.pid
fi

if ls "$ROOT/pids"/node-*.pid >/dev/null 2>&1; then
  echo "  ✗ existing pids found. run ./down.sh first, or ./up.sh $N --fresh to wipe."
  exit 1
fi

# Phase 1: init each node so their identities exist. We need node 0's ID
# before we can write the seed list for node 1..N-1.
echo "  → initialising $N nodes"
for i in $(seq 0 $((N-1))); do
  dir="$ROOT/node-$i"
  mkdir -p "$dir"
  if [[ ! -f "$dir/identity.toml" ]]; then
    "$BIN" --data-dir "$dir" init --defaults --force >/dev/null
  fi
done

# Extract node 0's identity from the TOML it wrote.
node0_id="$(grep -oE '[A-Za-z0-9]{60,}' "$ROOT/node-0/identity.toml" | head -n1)"
if [[ -z "$node0_id" ]]; then
  echo "  ✗ could not extract node 0 identity"
  exit 1
fi
echo "  genesis node-0 id: $node0_id"

# Phase 2: rewrite each non-genesis node's config.toml with node 0 as DHT seed.
genesis_port=$((DHT_BASE + 0))
for i in $(seq 1 $((N-1))); do
  dir="$ROOT/node-$i"
  cat > "$dir/config.toml" <<EOF
# devnet node-$i generated by up.sh
sigma_over_p   = 2.0
batch_size     = 100000
bootstrap_peers = []
n_nodes        = 10

[[dht_seeds]]
id   = "$node0_id"
addr = "127.0.0.1:$genesis_port"
EOF
done

# Phase 3: launch. Genesis first so later seeds can reach it; brief pause.
launch() {
  local i=$1
  local dir="$ROOT/node-$i"
  local chan=$((CHANNEL_BASE + i))
  local dht=$((DHT_BASE + i))
  local admin=$((ADMIN_BASE + i))
  local log="$ROOT/logs/node-$i.log"
  local pidf="$ROOT/pids/node-$i.pid"

  nohup "$BIN" \
    --data-dir "$dir" \
    --listen "127.0.0.1:$chan" \
    --dht-listen "127.0.0.1:$dht" \
    --admin-listen "127.0.0.1:$admin" \
    --config "$dir/config.toml" \
    > "$log" 2>&1 &
  echo $! > "$pidf"
  echo "  node-$i started pid=$(cat "$pidf") chan=$chan dht=$dht admin=$admin"
}

launch 0
sleep 0.3
for i in $(seq 1 $((N-1))); do
  launch $i
done

echo ""
echo "  $N nodes up. Admin endpoints:"
for i in $(seq 0 $((N-1))); do
  echo "    node-$i: http://127.0.0.1:$((ADMIN_BASE + i))/health"
done
echo ""
echo "  logs: $ROOT/logs/node-*.log"
echo "  shutdown: $ROOT/scripts/down.sh"
