//! # Liu ITS Channel
//!
//! A single bidirectional channel between two peers, continuously
//! generating ITS key material via Gaussian noise exchange.

use liun_receipts::{OpRecorder, Role, OP_CHANNEL_BYTES};
use liuproto_core::gf61::Gf61;
use liuproto_core::identity::NodeId;
use liuproto_core::mac;
use liuproto_core::noise;
use liuproto_core::pool::Pool;
use std::sync::Arc;
use tokio::net::TcpStream;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tracing::{debug, warn};
use crate::wire::{Frame, FRAME_SIZE};

/// Optional hook: credit bytes generated on this channel to a
/// long-running session on the provided recorder. Caller supplies the
/// counterparty's `NodeId` (not derivable from `peer_id: u64`), our
/// role for the session, and the current epoch.
#[derive(Clone)]
pub struct ChannelReceiptHook {
    pub recorder: Arc<OpRecorder>,
    pub counterparty: NodeId,
    pub my_role: Role,
}

/// Channel configuration parameters.
#[derive(Debug, Clone)]
pub struct ChannelConfig {
    /// Number of exchanges per batch (B).
    pub batch_size: usize,
    /// Number of batches per connection.
    pub n_batches: usize,
    /// Modulus multiplier: p = mult * sigma_z.
    pub mod_mult: f64,
    /// Band-limiting cutoff frequency.
    pub cutoff: f64,
    /// Number of sigma verification rounds.
    pub n_test_rounds: usize,
}

impl Default for ChannelConfig {
    fn default() -> Self {
        Self {
            batch_size: 100_000,
            n_batches: 1,
            mod_mult: 0.5,
            cutoff: 0.1,
            n_test_rounds: 2,
        }
    }
}

/// Channel status.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChannelStatus {
    /// Channel is running and producing key material.
    Active,
    /// Channel is idle (PSK held, ready to resume).
    Idle,
    /// Channel has been closed or peer departed.
    Closed,
}

/// A Liu ITS channel to a specific peer.
pub struct Channel {
    /// Peer identifier.
    pub peer_id: u64,
    /// Channel status.
    pub status: ChannelStatus,
    /// Configuration.
    pub config: ChannelConfig,
    /// OTP pool (manages key material).
    pool: Pool,
    /// Total key bits generated.
    pub total_bits: u64,
    /// TCP stream (if connected).
    stream: Option<TcpStream>,
    /// Optional receipt hook — credits bytes produced to an OpRecorder.
    receipt_hook: Option<ChannelReceiptHook>,
}

impl Channel {
    /// Create a new channel from a pre-shared key.
    pub fn new(peer_id: u64, psk: &[u8], nonce: &[u8; 16], config: ChannelConfig) -> Self {
        Self {
            peer_id,
            status: ChannelStatus::Idle,
            config,
            pool: Pool::from_psk(psk, nonce),
            total_bits: 0,
            stream: None,
            receipt_hook: None,
        }
    }

    /// Attach an optional receipt hook. Each successful `run_batch`
    /// call credits the generated bytes to a long-running session
    /// with the counterparty on the provided `OpRecorder`.
    ///
    /// Channels are by design symmetric — both endpoints produce the
    /// same number of key bits — so both sides call this with their
    /// own role. Aggregator pairs by `session_id` at epoch close.
    pub fn with_receipt_hook(mut self, hook: ChannelReceiptHook) -> Self {
        self.receipt_hook = Some(hook);
        self
    }

    /// Connect to peer and start key generation.
    pub async fn connect(&mut self, addr: &str) -> Result<(), Box<dyn std::error::Error>> {
        let stream = TcpStream::connect(addr).await?;
        stream.set_nodelay(true)?;
        self.stream = Some(stream);
        self.status = ChannelStatus::Active;
        debug!(peer = self.peer_id, "channel connected");
        Ok(())
    }

    /// Accept an incoming connection.
    pub fn accept(&mut self, stream: TcpStream) {
        let _ = stream.set_nodelay(true);
        self.stream = Some(stream);
        self.status = ChannelStatus::Active;
        debug!(peer = self.peer_id, "channel accepted");
    }

    /// Run one batch of the signbit_nopa protocol.
    /// Returns the number of key bits generated.
    pub async fn run_batch(&mut self) -> Result<usize, Box<dyn std::error::Error>> {
        let stream = self.stream.as_mut().ok_or("not connected")?;
        let b = self.config.batch_size;

        // Generate Gaussian noise
        let sigma_z = estimate_sigma_z(self.config.cutoff);
        let modulus = self.config.mod_mult * sigma_z;
        let z_samples = noise::batch_gaussian(b);

        // Compute wire values: w = Z mod p
        let wire_values: Vec<f64> = z_samples.iter()
            .map(|&z| noise::mod_reduce(z * sigma_z, modulus))
            .collect();

        // Extract sign bits
        let sign_bits: Vec<u8> = z_samples.iter()
            .map(|&z| noise::sign_bit(z))
            .collect();

        // Get OTP and encrypt sign bits
        let otp = self.pool.withdraw_otp(b);
        let sign_enc: Vec<u8> = sign_bits.iter().zip(otp.iter())
            .map(|(&s, &o)| s ^ o)
            .collect();

        // Compute MAC
        let (r, s) = self.pool.mac_keys();
        let wa: Vec<f64> = wire_values.clone();
        let wb = vec![0.0f64; b]; // placeholder — real protocol exchanges with peer
        let coeffs = mac::quantize_to_coeffs(&[wa.as_slice(), wb.as_slice()].concat(), sigma_z, 4, 4.0);
        // Append encrypted sign bytes
        let mut all_coeffs = coeffs;
        for chunk in sign_enc.chunks(8) {
            let mut byte_val = 0u64;
            for &bit in chunk {
                byte_val = byte_val * 2 + bit as u64;
            }
            all_coeffs.push(Gf61::new(byte_val));
        }
        let tag = mac::mac_tag(&all_coeffs, r, s);

        // Send wire values + encrypted signs + tag
        // (In full protocol: exchange with peer, verify their tag)
        let mut send_buf = Vec::with_capacity(b * 8 + sign_enc.len() + 8);
        for &w in &wire_values {
            send_buf.extend_from_slice(&w.to_be_bytes());
        }
        send_buf.extend_from_slice(&sign_enc);
        send_buf.extend_from_slice(&tag.val().to_be_bytes());
        stream.write_all(&send_buf).await?;

        // Deposit sign bits and recycle MAC key
        if sign_bits.len() >= 128 {
            self.pool.deposit(&sign_bits);
        }

        self.total_bits += b as u64;

        // Receipt hook: credit the generated bytes to the
        // long-running session with this counterparty.
        if let Some(hook) = &self.receipt_hook {
            let bytes_generated = (b as u64 + 7) / 8;
            hook.recorder.observe_peer(
                hook.counterparty,
                hook.my_role,
                OP_CHANNEL_BYTES,
                bytes_generated,
            );
        }

        debug!(peer = self.peer_id, bits = b, total = self.total_bits, "batch complete");
        Ok(b)
    }

    /// Get available key material in the pool.
    pub fn available_bytes(&self) -> usize {
        self.pool.available()
    }

    /// Close the channel.
    pub fn close(&mut self) {
        self.status = ChannelStatus::Closed;
        self.stream = None;
        debug!(peer = self.peer_id, "channel closed");
    }
}

/// Estimate sigma_z from cutoff frequency (Parseval scaling).
fn estimate_sigma_z(cutoff: f64) -> f64 {
    (2.0 * cutoff).sqrt()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_channel_creation() {
        let psk = vec![0u8; 1032];
        let nonce = [0u8; 16];
        let ch = Channel::new(1, &psk, &nonce, ChannelConfig::default());
        assert_eq!(ch.peer_id, 1);
        assert_eq!(ch.status, ChannelStatus::Idle);
        assert_eq!(ch.total_bits, 0);
    }

    #[test]
    fn test_sigma_z() {
        let sigma = estimate_sigma_z(0.1);
        assert!((sigma - (0.2f64).sqrt()).abs() < 1e-10);
    }

    #[test]
    fn with_receipt_hook_is_optional_and_accepts() {
        // Just verify the builder compiles and attaches. Real batch-run
        // credit is covered by the e2e manager test.
        use liun_receipts::SharedKey;
        let psk = vec![0u8; 1032];
        let nonce = [0u8; 16];
        let recorder = Arc::new(OpRecorder::new(
            NodeId::generate(),
            SharedKey::from_bytes(vec![0u8; 4096]),
        ));
        let hook = ChannelReceiptHook {
            recorder,
            counterparty: NodeId::generate(),
            my_role: Role::Server,
        };
        let ch = Channel::new(1, &psk, &nonce, ChannelConfig::default())
            .with_receipt_hook(hook);
        assert!(ch.receipt_hook.is_some());
    }
}
